# -*- coding: utf-8 -*-
"""22-PySpark Sample.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vku3GCMD2ZAWqGEXsIUw0NmdqF-Y9am2
"""

from pyspark.sql import SparkSession
spark = SparkSession.builder \
    .master("local[1]") \
    .appName("PySpark") \
    .getOrCreate()

df=spark.range(100)
print(df.sample(0.06).collect())

print(df.sample(0.1,123).collect())
print(df.sample(0.1,123).collect())
print(df.sample(0.1,456).collect())

#with Duplicates
print(df.sample(True,0.3,123).collect())
#No duplicates
print(df.sample(0.3,123).collect())

df2=df.select((df.id % 3).alias("key"))
print(df2.sampleBy("key", {0: 0.1, 1: 0.2},0).collect())

rdd = spark.sparkContext.range(0,100)
print(rdd.sample(False,0.1,0).collect())
print(rdd.sample(True,0.3,123).collect())

print(rdd.takeSample(False,10,0))
print(rdd.takeSample(True,30,123))

