# -*- coding: utf-8 -*-
"""32-Read & Write parquet File.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19j0lFbE8Y45Yi5D3QRU0HRwXwF2GuWW0
"""

data =[("James ","","Smith","36636","M",3000),
              ("Michael ","Rose","","40288","M",4000),
              ("Robert ","","Williams","42114","M",4000),
              ("Maria ","Anne","Jones","39192","F",4000),
              ("Jen","Mary","Brown","","F",-1)]
columns=["firstname","middlename","lastname","dob","gender","salary"]
df=spark.createDataFrame(data,columns)
df.printSchema()
df.show(truncate=False)

df.write.parquet("/tmp/output/People.parquet")

parDF=spark.read.parquet("/tmp/output/People.parquet")

df.write.mode('append').parquet("/tmp/output/people.parquet")

df.write.mode('overwrite').parquet("/tmp/output/people.parquet")

df.createOrReplaceTempView("ParquetTable")
spark.sql("select * from ParquetTable where salary >= 4000 ").show()

spark.sql("CREATE TEMPORARY VIEW PERSON USING parquet OPTIONS (path \"/tmp/output/people.parquet\")")
spark.sql("SELECT * FROM PERSON").show()

df.write.partitionBy("gender","salary").mode("overwrite").parquet("/tmp/output/people2.parquet")

parDF2=spark.read.parquet("/tmp/output/people2.parquet/gender=M")
parDF2.show(truncate=False)

spark.sql("CREATE TEMPORARY VIEW PERSON2 USING parquet OPTIONS (path \"/tmp/output/people2.parquet/gender=F\")")
spark.sql("SELECT * FROM PERSON2" ).show()

